openapi: 3.0.1
info:
  version: 1.0.0
  title: WikiForge REST API
  description: >
      This API provides cacheable and straightforward access to
      WikiForge content and data, in machine-readable formats.

      ### Global Rules

      - Limit your clients to no more than 200 requests/s to this API.
        Each API endpoint's documentation may detail more specific usage limits.
      - Set a unique `User-Agent` or `Api-User-Agent` header that
        allows us to contact you quickly. Email addresses or URLs
        of contact pages work well.

      By using this API, you agree to WikiForge's
      [Terms of Service](https://hub.wikiforge.net/wiki/Terms_of_Service) and
      [Privacy Policy](https://hub.wikiforge.net/wiki/Privacy_Policy).

  termsOfService: https://hub.wikiforge.net/wiki/Terms_of_Service
  contact:
    name: the WikiForge Staff team
    url: https://hub.wikiforge.net
  license:
    name: Apache2
    url: http://www.apache.org/licenses/LICENSE-2.0
# Override the base path for host-based (proxied) requests. In our case,
# we proxy https://{domain}/api/rest_v1/ to the API.
x-host-basePath: /api/rest_v1
x-route-filters:
  - path: lib/content_location_filter.js
  - path: ./lib/normalize_title_filter.js
    options:
      redirect_cache_control: '{{options.purged_cache_control}}'
paths:
  /page:
    x-modules:
      - path: v1/content.yaml
        options:
          response_cache_control: '{{options.purged_cache_control}}'
      - path: v1/pdf.js
        options: '{{options.pdf}}'
      - path: v1/common_schemas.yaml # Doesn't really matter where to mount it.
  /transform:
    x-modules:
      - path: v1/transform.yaml
  /data:
    x-modules:
      - path: v1/citoid.js
        options: '{{options.citoid}}'
